### ISSUE TITLE
 Error: No compatible version found: handlebars@'file:vendor/handlebars'

### ISSUE THREAD

**Issue by mrfrasier** [SparkPost/mandrill-sparkpost-templates#12]
Anyone else hitting this issue when running npm install?

npm ERR! Error: No compatible version found: handlebars@'file:vendor/handlebars'
npm ERR! Valid install targets:
npm ERR! ["1.0.6","1.0.6-2","1.0.7","1.0.8","1.0.9","1.0.10","1.0.11","1.0.12","1.1.0","1.1.1","1.1.2","1.2.0","1.2.1","1.3.0","2.0.0-alpha.1","2.0.0-alpha.2","2.0.0-alpha.3","2.0.0-alpha.4","2.0.0-beta.1","2.0.0","3.0.0","3.0.1","3.0.2","3.0.3","4.0.0","4.0.1","4.0.2","4.0.3","4.0.4","4.0.5","1.0.2-beta","1.0.4-beta","1.0.5-beta"]
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by ewandennis** [comment]
@mrfrasier - that looks like an NPM error [related to package version specifiers](https://github.com/npm/npm/issues/7967) in `package.json`.  As that issue thread suggests, could you try updating NPM?  It would also be very helpful to know which version you currently have so we can avoid the issue in future.  Thanks!

**Comment by mrfrasier** [comment]
This can be closed. We spent the day migrating manually, only to have our account suspended and needing to go back to mandrill anyway
