### ISSUE TITLE
Render SparkPost templates locally

### ISSUE THREAD

**Issue by generalov** [SparkPost/mandrill-sparkpost-templates#13]
Hi! We are using [handlebars](https://www.npmjs.com/package/handlebars) template engine to render Mandrill's templates locally because them templates just the handlebars. :) It helps our in writing unit tests and documentation. 

We would like to use SparkPost. Unit tests could help. But SparkPost templates has differences and handlebars throws syntax errors on `{{each}}` `{{if }}` and etc. instrutions. 

Is it possbile to render SparkPost templates locally? I've looked for some documentation, library or may be handlebars configuration, but found nothing yet.

**Comment by ewandennis** [comment]
Thats a good question.  SparkPost's template language isn't open source today (but I'll certainly feed that back).  If you don't mind making REST API calls in your test suite, you can use the SparkPost API `templates` endpoint to [create](https://developers.sparkpost.com/api/#/reference/templates/create-and-list) and then [preview](https://developers.sparkpost.com/api/#/reference/templates/preview) a template.
