### ISSUE TITLE
Support of Conditional Merge Tags

### ISSUE THREAD

**Issue by bconneen** [SparkPost/mandrill-sparkpost-templates#14]
Is there any plan to support "Conditional Merge Tags" during translation from Mandrill->SparkPost?

https://mandrill.zendesk.com/hc/en-us/articles/205582527-About-Dynamic-and-Conditional-Merge-Tags

Unfortunately a large number of our templates use them, and it's proving to be a paint o manually correct this.

**Comment by ewandennis** [comment]
Yup.  Check out Issues #6 and PR #8.
