### ISSUE TITLE
SparkPost API key requires template write permission

### ISSUE THREAD

**Issue by alexgbernier** [SparkPost/mandrill-sparkpost-templates#15]
Documentation should state the SparkPost API key requires template read/write permission before the migration tool will work. My default API key didn't have this permission and I got a "Forbidden" error response.

**Comment by ewandennis** [comment]
The migration page of the tool itself includes the following text: `Requires Templates Read/Write privileges` but it should also be called out on the migrate API section of the README.  Thanks for the note!

**Comment by ewandennis** [comment]
README updated.
