### ISSUE TITLE
Error on deploying to Heroku

### ISSUE THREAD

**Issue by apitts** [SparkPost/mandrill-sparkpost-templates#21]
I receive this error message: "Couldn't find either the add-on service or the add-on plan of "sparkpost"."

**Comment by ewandennis** [comment]
@apitts Could you please try removing `sparkpost` from the `addons` list in `app.json`? That will stop the SparkPost addon from being included in your Heroku app.

**Comment by apitts** [comment]
Thanks @ewandennis! I actually just ended up cloning the repo and running locally with no major issues.
