### ISSUE TITLE
Unless

### ISSUE THREAD

**Issue by apitts** [SparkPost/mandrill-sparkpost-templates#22]
Could {{#unless x}} {{/unless}} not just be replaced with {{if not x}} {{end}}?

**Comment by ewandennis** [comment]
On the surface it looks that way, doesn't it? I suspect we didn't add that due to questions about truthy and falsey values in SparkPost and Mandrill's Handlebars respectively.

If you have some good test cases, they'd make a good basis for a pull request ;)

**Comment by apitts** [comment]
Thanks @ewandennis! Yeah, that makes sense. My variables are all just simple booleans. I only had two templates with unless so I ended up just deleting the unless lines before using the migration tool then adding them back in as {{if not x}}{{end}} afterwards. Seems to be working OK.

**Comment by ewandennis** [comment]
Good to hear @apitts. I'm glad you're up and running.
